architecture: 1
architecture_list:
- Oracle
- CNN
- Pre-trained
architecture_mode: original
batch: 
clip_param: 0.1
cpu: 0
cuda: 1
distractors: 0
entropy_coef: 0
eps: 1.0e-05
eval_interval: 500
gae_lambda: 0.95
gamma: 0.99
gcp_bucket_name: jslee_1210_2024_0528_rl_training
gcp_key: /home/jupyter/burnished-city-422610-g3-6e5fb4c4e617.json
load_model: false
load_weight_name: SpritesState-v0
log_comment: more channels fine tuning
log_dir: logs
log_interval: 1
lr: 0.0002
max_grad_norm: 0.5
mps: 0
num_env_steps: 5000000
num_mini_batch: 32
num_processes: 32
num_steps: 120
package_no: 1
ppo_epoch: 8
recurrent_policy: false
save_dir: model_weights
save_interval: 500
save_name: CNN_PPO_0_distractors
save_weight_name: SpritesState-v0
seed: 100
upload_to_gcp: false
upload_to_gcp_batch: true
use_gae: true
use_linear_lr_decay: true
use_proper_time_limits: true
value_loss_coef: 0.5
view_video_interval: 20
visualize: false
